### ISSUE TITLE
sfx hover de torres y wave icon

### ISSUE THREAD

**Issue by gantana** [cigumo/krvi#103]
sfx del hover de las torres o el wave icon suena mas de lo que deberia y a veces cuando tengo el mouse en otro lugar.

Incluso suena cuando tengo el comic a la vista.

**Comment by cigumo** [comment]
@gantana te referis al volumen o a que se dispara solo?
sonido a traves de comic: se arreglo con #96

**Comment by cigumo** [comment]
el hover de las torres suena al salir tambien! y el de los terrains no suena.

**Comment by cigumo** [comment]
se escucha el sonido de KRQuickMenuItem::showTooltip()

**Comment by cigumo** [comment]
fixed in 1.9.9.8
