### ISSUE TITLE
ultimate_hero_asra - offset

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#122]
arrows don't fall right on the aimed spot.
same on mobile.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43391939/93738409-ad028d00-fc20-11ea-9c50-e23d4da63b48.gif)

**Comment by cigumo** [comment]
![Screen Recording 2020-09-28 at 9 58 01 PM mov](https://user-images.githubusercontent.com/934821/94500667-4e1bb580-01d6-11eb-8855-46c156999c17.gif)

**Comment by cigumo** [comment]
![Screen Recording 2020-09-28 at 10 05 01 PM mov](https://user-images.githubusercontent.com/934821/94500881-c97d6700-01d6-11eb-873d-e3c68300d4eb.gif)

**Comment by cigumo** [comment]
mitigated in 1.9.9.10
