### ISSUE TITLE
encyclopedia tower cooldown 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#126]
COOLDOWN_0 = "Very Slow"  >= 2.0s
COOLDOWN_1 = "Slow"          >= 1.5s
COOLDOWN_2 = "Average"    >= 0.8s
COOLDOWN_3 = "Fast"          >= 0.5s
COOLDOWN_4 = "Very Fast"    < 0.5s

TOWER_DARK_ARMY_ARCHER: Very Fast -> Fast
TOWER_EMBER_LORDS_MAGE: Average -> Slow
TOWER_WARMONGER_BALLOON: Very Fast ->  Average
TOWER_FALLEN_ONES_BONE_FLINGERS: Very Fast -> Fast
TOWER_DEEP_DEVILS: Average -> Slow

**Comment by cigumo** [comment]
duplicate of #113
