### ISSUE TITLE
pc: barracks not showing current range when selected

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#131]
Shadow Archers, Swamp Thing, Infernal Mage show it.
![20200921213723_1](https://user-images.githubusercontent.com/43391939/93768027-beb15800-fc53-11ea-9b94-7ec082ab930f.jpg)
Goblin War Zeppelin doesn't
![20200921213728_1](https://user-images.githubusercontent.com/43391939/93768090-de488080-fc53-11ea-9830-dbeef10bd2a5.jpg)

wicked_sisters_brumstick_upgrade doesnt either. (unlike kr2's falconer upgrade which shows how much the range gets increased)
![20200922073518_1](https://user-images.githubusercontent.com/43391939/93828429-432cc680-fca6-11ea-9904-374bd23740e8.jpg)

**Comment by cigumo** [comment]
Zepellins and Wicked sisters are a kind of barracks, so they use the barrack logic for the range. 
It's not easy to change.

**Comment by sunnydaler** [comment]
Good on mobile
![Vengeance_2020-10-07-21-38-45](https://user-images.githubusercontent.com/43391939/95336524-bf045100-08eb-11eb-9394-33982a7984c1.jpg)
![Vengeance_2020-10-07-21-39-16](https://user-images.githubusercontent.com/43391939/95336536-c0ce1480-08eb-11eb-8a6b-0337b4aea32c.jpg)

**Comment by cigumo** [comment]
fixed in 1.9.9.13
