### ISSUE TITLE
wicked sisters' info box shows 0-0 damage value

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#137]
![20200921215330_1](https://user-images.githubusercontent.com/43391939/93768838-f5d43900-fc54-11ea-94bc-7cf05e4f6f25.jpg)
![20200921214812_1](https://user-images.githubusercontent.com/43391939/93768845-f8369300-fc54-11ea-8830-40d509161992.jpg)

**Comment by cigumo** [comment]
fixed in 1.9.9.10
