### ISSUE TITLE
wicked_sisters_poison modifier

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#141]
- [ ]  some modifiers of override it.

1. ultimate_hero_tank

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/43391939/94144841-9ec8a100-feac-11ea-9392-185c8a069a50.gif)

2. flaming trident's modifier_burn 
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/43391939/93833907-061c0080-fcb5-11ea-9db7-7eeb765f717e.gif)

3. murglun_infernal_heat
https://cdn.discordapp.com/attachments/750507657613410354/758672219709767690/ezgif.com-resize_2.mp4

4. hero_beresad's conflagration
https://cdn.discordapp.com/attachments/750507657613410354/758679453806100480/ezgif.com-resize_3.mp4

5. hero_naga's ultimate
https://cdn.discordapp.com/attachments/750507657613410354/759351689077325844/ezgif.com-resize_5.mp4

- [ ] damage is not affected by any damage increase upgrade (supreme_architects_system) or aura_with_towers (Melting Furnace IV's abrasive_heat, Oloch's hellish_infusion, Murglun's tar_maker)

**Comment by Mmlh1** [comment]
All fixed in 1.15.0
