### ISSUE TITLE
review screen shake intensity

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#144]
https://cdn.discordapp.com/attachments/750507657613410354/757781036800409620/2020_09_22_10_47_17_550_new.mp4
jigou_earthshake
soul impact

these two shake the screen for several seconds 
and it would be nicer if the effect were subtle.

**Comment by cigumo** [comment]
reduced shake to half amount for PC build

**Comment by cigumo** [comment]
fixed in 1.9.9.13
