### ISSUE TITLE
adjust safe_nodes for frog_chaser_jump on pc

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#145]
it is 80 nodes to exit on mobile. and needs to be adjusted on pc version which has extended paths on sides.
Chasers spawn in stages 17, 18, 19 which have exits on  west or east.
>			<key>skills</key>
>			<array>
>				<dict>
>					<key>key</key>
>					<string>move_to_unit</string>
>					<key>safe_nodes_to_exit</key>
>					<integer>80</integer>

![desktop](https://user-images.githubusercontent.com/43391939/93838226-e0e2be80-fcc3-11ea-8853-d63b65c33c72.gif)
![mobile](https://user-images.githubusercontent.com/43391939/93838337-4171fb80-fcc4-11ea-9e0e-b218e7c4a618.gif)

**Comment by cigumo** [comment]
hard because:
- should be tested after the unit has a valid path
- affects many enemies unless solved only for move_to_unit, which means potential bugs

**Comment by cigumo** [comment]
fixed in 1.9.9.13
