### ISSUE TITLE
encyclopedia information issues

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#149]
- [x] Paragon gets magic aura from Devoted Priest so does not show in stats
- [x] Damage for scaling attacks
  - bone flingers
  - blazing gems
  - others.
- [x] Troop captain: remove "medium damage" from special abilities
- [x] Twin ghosts: magic resistance not shown
  - ![](https://cdn.discordapp.com/attachments/750507657613410354/757850544415965214/Shouldnt_both_of_them_have_immune_or_great_resistances.jpg)
- [x] Twin ghosts should show "max. armor" or similar because they have 100 points
- [x] Three soldiers in encyclopedia image for
  - Dark Knights
  - Harassers
- [x] ENEMY_BOSS_WINTER_QUEEN_ENCYC_DESCRIPTION = "Free from her shackles, she is an powerful creature with only one thing in mind: to turn the kingdom into a frozen nightmare."
an --> a

**Comment by cigumo** [comment]
fixed in 1.9.9.10

**Comment by TGM2674** [comment]
All mages tower has their dmg. icon displayed as a sword (physical dmg) rather than a magical orb (magic dmg) in encyclopedia

**Comment by TGM2674** [comment]
Goblin War Zeppelin's rally range is "short"-"short"-"short"-"short" from level 1-4
