### ISSUE TITLE
feedback billy

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#150]

**Comment by vanzen** [comment]
![krv_bug](https://user-images.githubusercontent.com/2745271/93921038-64150c00-fce6-11ea-99a7-dab10a741fbe.jpg)

Despues de tirar el poder quedo un efecto en pantalla sin irse por el resto de la partida.

**Comment by vanzen** [comment]
Controles in game
- Botón derecho puede servir como CANCEL cuando tenes seleccionado un poder.

Stage Victory 
- Podría demorar un poquito menos en arrancar.
- El fondo negro transparente aparece un poco brusco transparente y queda un segundo sin que pase nada.
--- Se podría hacer fade del negro transparente y largar la animación de victory antes.

Torre Demons
- Esto es ultra detalle fino: Cuando dispara en algunos casos parece que el proyectil sale del centro en vez de las manos, eso pasa porque el trail del proyectil ya aparece cuando spawnea y no cuando se mueve, da una sensación de que el proyectil salio del centro. (ejemplo disparando hacia las 10am, se puede ver bien en la pantalla 1)

**Comment by vanzen** [comment]
Feedback opcional:

Main Menu > Es raro que si apreto START aparecen los Slots, pero sigue el START ahi. Al principio me confundio un poco.
Options > Tambien me confundio un poco que el Options desde el MAPA diga Main Menu, no se si no lo cambiaria a QUIT. Inicialmente buscaba el Quit.

**Comment by cigumo** [comment]
pasados a issues individuales.
