### ISSUE TITLE
arcane_magus shouldn't cast teleport when possessed.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#161]
Might need the following codes 
>					<key>dont_cast_while_have_modifiers_id</key>
>					<array>
>						<string>spirit_mausoleum_modifier_possesion</string>
>					</array>

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43391939/94210389-8c308500-ff09-11ea-80c7-a45fb2e1cf37.gif)

**Comment by cigumo** [comment]
fixed in 1.9.9.13
