### ISSUE TITLE
deep_devils tower range display

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#162]
displays its soldiers' rally range (290 in dm.) in blue color as a preview when the hand pointer hovers over the build icon or the upgrade icon.

shows its shooter's attack range (300 in dm.) in green color when clicked the rally change icon.

same on mobile.

**Comment by cigumo** [comment]
- preview (initial build / upgrade) should show firing range
- rally change should show rally range

**Comment by cigumo** [comment]
fixed in 1.9.9.10
