### ISSUE TITLE
leak-alert badge display

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#166]
mobile: https://cdn.discordapp.com/attachments/750507657613410354/759073325569146890/YouCut_20200926_002426236.mp4

desktop: https://cdn.discordapp.com/attachments/750507657613410354/759073433865945160/2020_09_26_00_21_02_474_new.mp4

pc version shows the badge in different ways
-displays the badge for enemies that have exited the map, too
-doesn't display for all enemies that are out of the screen(camera) unless they approach near a border of the map

**Comment by cigumo** [comment]
fixed both in 1.9.9.10
