### ISSUE TITLE
last rally point data of a tower holder is not discard upon selling

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#167]
https://cdn.discordapp.com/attachments/750507657613410354/759354841767870464/ezgif.com-resize_6.mp4
https://cdn.discordapp.com/attachments/750507657613410354/759396204512935956/ezgif.com-resize_7.mp4

**Comment by cigumo** [comment]
Is this really a bug?

**Comment by AerisDraco** [comment]
I'd say yes since you can use it to send mobile towers beyond their intended maximum ranges. Easiest to test with a Nimbus 4000 Wicked Sisters and a Goblin War Zeppelin.

**Comment by cigumo** [comment]
yes it! 
https://cdn.discordapp.com/attachments/750507657613410354/759396204512935956/ezgif.com-resize_7.mp4

**Comment by cigumo** [comment]
fixed in 1.9.9.13
