### ISSUE TITLE
cannon_denas: cooldown and unblock_pay_description in stage 16 heroic/iron

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#168]
In heroic/iron mode, the cannon attack doesn't have a specified cooldown and the attacked tower is disabled forever. and the tower_unblock_pay_description doesn't appear when the disabled tower is clicked. 
TOOLTIP_TOWER_UNBLOCK_PAY_DESCRIPTION

in Campaign
![20200928132013_1](https://user-images.githubusercontent.com/43391939/94391790-79c87c80-0191-11eb-83c8-d860873c5b9c.jpg)
>			<key>modifier</key>
>			<dict>
>				<key>key</key>
>				<string>tower_block_brea</string>
>				<key>id</key>
>				<string>tower_block_pay</string>
>				<key>duration</key>
>				<integer>40</integer>
>				<key>pay_to_remove</key>
>				<true/>

>							<key>position</key>
>							<integer>4</integer>
>							<key>tooltip_key</key>
>							<string>TOOLTIP_TOWER_UNBLOCK_PAY</string>

in Heroic/Iron
![20200928133446_1](https://user-images.githubusercontent.com/43391939/94391780-733a0500-0191-11eb-8742-96aa281b4d59.jpg)
>			<key>modifier</key>
>			<dict>
>				<key>key</key>
>				<string>tower_block_brea</string>
>				<key>id</key>
>				<string>tower_block_pay</string>
>				<key>duration</key>
>				<integer>0</integer>
>				<key>pay_to_remove</key>
>				<true/>

>							<key>override_tooltip</key>
>							<dict>
>								<key>title_text</key>
>								<dict>
>									<key>text</key>
>									<string>HOLDER_FROZEN_LANDS_BLOCKED_NAME</string>
>								</dict>
>								<key>main_text</key>
>								<dict>
>									<key>text</key>
>									<string>HOLDER_FROZEN_LANDS_BLOCKED_DESC</string>
>								</dict>
>							</dict>

**Comment by cigumo** [comment]
@thehalfleprechaun this wasn't on purpose right?

**Comment by cigumo** [comment]
approved

**Comment by cigumo** [comment]
fixed in 1.9.9.10
