### ISSUE TITLE
suggested name changes / AerisDraco

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#171]

**Comment by AerisDraco** [comment]
My bad, forgot Frozen Land. That should be changed as well.

**Comment by AerisDraco** [comment]
Original Localization | Suggested Localization | Reasoning
------------ | ------------- | -------------
Devoted Priest | Devoted Priestess | -ess suffix indicates the enemy is female
Svell Druid | Mountain Druid | Svell prefix doesn't make sense, as _Svell_ is an Icelandic word meaning 'to swell', which has little to do with the enemy's function. Druid could also perhaps be switched, as Druids are a pre-existing race in Origins.
Frozen Land | Ice | Frozen Land doesn't sound good in English.
Chosen by the Sea | Chosen of the Sea | Chosen 'of' the Sea sounds slightly better than Chosen 'by' the Sea
Frozen Throat | Icy Breath | Frozen Throat doesn't translate well, and honestly throats aren't often given descriptions outside of 'sore throat'. Icy Breath also describes the ability's function better.
Fierce Breath | Frost Blast | Similarly, 'Fierce Breath' just sounds a bit weird, breath isn't known for being fierce, and it doesn't describe the ability's effect particularly well either.
Frosty | Avalanche | Frosty is non-indicative of the ability's function. Avalanche keeps the ice theme and reflects the snowball better.
Cold Fury | Permafrost | Cold Fury also doesn't exactly work in English. Permafrost better reflects the ability's function, and also draws parallels with Elora's similar ability from KR1.
Lava Blood | Magma Blood | Honestly this a pedantic change, but magma references molten rock inside the earth, so I've extended it to Murglun's blood.
Magma Pool | Lava Pool | Similar reason to the Lava Blood change, as lava is molten rock on the surface.
Geyser | Eruption | Though Geyser would work, Eruption fits a volcanic theme better. 
Eruption | Meteor Shower | Eruption makes no sense given the ability's function, which is summoning rocks from the sky. Meteor Shower better reflects the ability's animation. Alternatively, 'Cataclysm' could also work.

**Comment by cigumo** [comment]
Except Svell druid, the rest were all approved by @thehalfleprechaun

**Comment by cigumo** [comment]
done for english in 1.9.9.11
pending: localization ja, ru, zh-Hans, zh-Hant

**Comment by cigumo** [comment]
TODO: 
- [ ] include localizations
- [ ] there is already a meteor shower for the Orc Shaman tower

**Comment by cigumo** [comment]
also changed Spectral Mausoleum
fixed in 1.9.9.13
