### ISSUE TITLE
Tower Room Statistics

### ISSUE THREAD

**Issue by AerisDraco** [cigumo/krvi#172]
- [x] Swamp Thing displays improper statistics in Tower Room (Displays medium attack, medium-high HP, low armor; should be high attack, high HP, no armor)

- [x] Blazing Gem suffers from the same issue as the encyclopedia where the damage display corresponds to its 3rd tier of scaling

- [ ] Suggestion: Add multiple information bars for hybrid towers (Deep Devils' Reef, Swamp Thing) to reflect both of their modes

- [ ] Suggestion: Retool the information to reflect the Tier 4 version of each tower. Currently it reflects the Tier 1 version, which is fairly worthless since T1 towers are rarely used and the game itself recommends against it in the loading tips

**Comment by cigumo** [comment]
I added changes made by Sunnydaler to the tower room stats, which somehow fix the first to items. 
The suggestion require changes to the UI which I can't do at this point.
