### ISSUE TITLE
next wave icon appears and tower menu gets closed

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#173]
![1](https://user-images.githubusercontent.com/43391939/94503120-b2735f00-0240-11eb-97b3-46e595888178.gif)
![2](https://user-images.githubusercontent.com/43391939/94503121-b30bf580-0240-11eb-9ebe-f74720b6df80.gif)

**Comment by cigumo** [comment]
can't reproduce it

**Comment by sunnydaler** [comment]
Top: click a holder and open tower menu. move the mouse pointer away from a tower icon (it should stay inside the menu ui thou) just when the wave icon appears. 
Bottom: click a holder and open menu. Move away cursor after the wave icon appears

**Comment by cigumo** [comment]
https://cdn.discordapp.com/attachments/493772773081219073/764101475461758986/KRV_failed_upgrade.mp4

**Comment by sunnydaler** [comment]
https://steamcommunity.com/app/1367550/discussions/0/2968393780775727055/

**Comment by cigumo** [comment]
It happens when: 
- quick menu: the mouse is in movement over a quick menu icon and the wave flag appears
- power: the mouse is moved when the wave flag appears

**Comment by cigumo** [comment]
fixed in 1.9.9.16
