### ISSUE TITLE
Rally pointer over the X sign in unselectable area / Grunty

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#176]
![Screenshot_20201002-003959_Discord](https://user-images.githubusercontent.com/43391939/94831717-02704280-0448-11eb-954a-e7d9060751ad.jpg)

**Comment by sunnydaler** [comment]
Grunty said "when you hold the rally without releasing the cursor appears like that again"

**Comment by cigumo** [comment]
fixed the hand part of it in #199 
I will leave the rally + X as it is
