### ISSUE TITLE
upgrade is blocked on towers that are locked but featured as bonus 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#180]
Rotten Forest is introduced first in stage 11 iron. 
However, you can't upgrade them if you haven't finished stage 13 yet. 

Same for Goblin War Zeppelin which appears first in stage 6 iron. This tower unlocks upon completing stage 14.

![20201002221134_1](https://user-images.githubusercontent.com/43391939/94928101-20987a00-04fe-11eb-92ec-4e468f3fc00c.jpg)
![20201002220532_1](https://user-images.githubusercontent.com/43391939/94928106-21c9a700-04fe-11eb-9f73-4efd601601db.jpg)

**Comment by cigumo** [comment]
fixed in 1.9.9.13
