### ISSUE TITLE
Hero Tank's expendables block range and positioning 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#203]
The block range is so large at 240 that they get out of the tank's main attack range.
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/43391939/95089412-145f2780-075f-11eb-99c6-35991064de64.gif)

Besides, they stand where the tank is. Not in front of the tank. Unlike beastmaster's boars and elven female archer's wildcat.

**Comment by cigumo** [comment]
level 3 expendables have range 120. changed level 1 ones to 120 too. 
fixed in 1.9.9.13
