### ISSUE TITLE
instakills attempted on bosses

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#208]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/43391939/95395117-d289d900-0938-11eb-8666-fdf77d759875.gif)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/43391939/96518473-f5f04480-12a5-11eb-83db-da4d0fc3af77.gif)

dark_army_blazing_mage_destructo_upgrade

hero beresad's remove_existence

swamp thing's instakill

probably because they are missing this?
>					<key>exclude_boss</key>
>					<true/>

**Comment by Mmlh1** [comment]
Fixed in 1.15.0.
