### ISSUE TITLE
no tower available in tutorial stage 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#212]
![2020_10_09_14_55_30_437](https://user-images.githubusercontent.com/43391939/95549334-0ac90e80-0a42-11eb-85e4-2b3c2653e922.png)
![2020_10_09_15_19_05_714](https://user-images.githubusercontent.com/43391939/95549761-d144d300-0a42-11eb-9376-8a1206959298.png)

how i did:
quit the game in the middle of the tutorial while playing on a new slot. 
enter the tutorial stage again.
https://streamable.com/mswv9s
https://streamable.com/nhl6ba

**Comment by cigumo** [comment]
fixed in 1.9.9.14
