### ISSUE TITLE
relocking issue after playing stage 5 in iron / Danche

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#214]
- completed the campaign
- after playing stage 5 iron
  - the 5th tower slot got relocked
  - dark knights get relocked
- restarting the game fixes the issue

**Comment by sunnydaler** [comment]
Right after finishing stage 14 iron, I re-entered the iron stage. and the orc shaman slot is locked.
![20201009231027_1](https://user-images.githubusercontent.com/43391939/95596312-2fe07000-0a88-11eb-8cb4-41b0f55208d7.jpg)
it fixed itself when i exited to the world map and re-entered the iron.

**Comment by cigumo** [comment]
fixed both in 1.9.9.14
