### ISSUE TITLE
anurians jump counts corpses and flying enemies

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#221]
https://cdn.discordapp.com/attachments/493772773081219073/765934110505697320/YouCut_20201014_224704444.mp4

**Comment by sunnydaler** [comment]
Chasers jump requires 2 targets in an area. However, Chasers can jump onto one living enemy if other dead bodies/weapons are near the enemy.

**Comment by Mmlh1** [comment]
Yes, the shield is not the issue. The dead bodies nearby are. I didn't watch it correctly at first. Dead bodies should be ignored as targets for Chasers

**Comment by Mmlh1** [comment]
Flying units also count as targets, which is weird and probably a bug. Chasers will jump on Beresad's golem if he is overhead, and they will jump in the Zeppelin's Sapper if any flying hero is overhead.

**Comment by cigumo** [comment]
fixed in 1.9.9.19

**Comment by cigumo** [comment]
reverted in 1.15.5.4 due to a new general fix in #270
