### ISSUE TITLE
runes_of_powers_upgrade

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#257]
- [x] it seems that this upgrade affects only spirit_mausoleum and ember_lords. I haven't seen BLAST proc on the other mage towers.
![2020_10_21_21_44_53_691](https://user-images.githubusercontent.com/43391939/96721190-bd0bb900-13e6-11eb-81c7-a9c695c5a57d.png)

- [x] mausoleum's "BLAST" is not blue but yellow.

![2020_10_21_21_13_47_818](https://user-images.githubusercontent.com/43391939/96718708-5b961b00-13e3-11eb-8e2c-3e821785021c.png)
Found the problem. They put the same numbers as in pop_blast_critical_fire.
>	<key>pop_blast_critical_blue</key>
>	<dict>
>		<key>key</key>
>		<string>pop</string>
>		<key>color_inside</key>
>		<array>
>			<integer>255</integer> 
>			<integer>255</integer>  
>			<integer>153</integer>  
>		</array>
>		<key>color_outside</key>
>		<array>
>			<integer>253</integer>
>			<integer>160</integer>
>			<integer>6</integer>
>		</array>

should be
		<key>color_inside</key>
		<array>
			<integer>220</integer>
			<integer>245</integer>
			<integer>255</integer>
		</array>
		<key>color_outside</key>
		<array>
			<integer>41</integer>
			<integer>160</integer>
			<integer>209</integer>

**Comment by Mmlh1** [comment]
I think Deep Devils are also affected, but the other mages aren't

**Comment by Mmlh1** [comment]
Everything fixed in 1.15.0 except possibly the colour of the Mausoleum pop, will check that.

Edit: Maus pop is not fixed yet.

**Comment by Mmlh1** [comment]
Fixed in 1.15.0 including Maus pop
