### ISSUE TITLE
Visual glitch on Denas Castle top half

### ISSUE THREAD

**Issue by lolsith** [cigumo/krvi#266]
On both parts of this mission, selecting towers on the top section of the map causes a fast blur/shake of the entire screen. It’s very fast but noticeable and causes me nausea. It is not happening on any other maps.
Playing 1920x1080 60hz
-Not performance issue, 3.2Ghz 4core 970GTX
-happens with or without vsync on
-happens in 1920x1080 16bit too

**Comment by sunnydaler** [comment]
#246 duplicate
