### ISSUE TITLE
infernal_portal's min target requirement

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#270]
>					<key>crowds_target</key>
>					<dict>
>						<key>range</key>
>						<integer>120</integer>
>						<key>min_targets</key>
>						<integer>3</integer>
>						<key>find_max_crowd</key>
>						<true/>
>					</dict>

it looks like it is not working as designed.

teleports a single frozen heart (skeletons count too?) -- this gif is from mobile gameplay tho. difficult to reproduce the same condition.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/43391939/97416316-9ea73f80-1949-11eb-9d3c-5ff8adec4a92.gif)

1 each of frozen soul and frozen heart somehow meet the teleport requirement. -- from a gameplay on latest desktop version
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/43391939/97416917-67855e00-194a-11eb-9f23-3ea1813cf2ba.gif)

**Comment by sunnydaler** [comment]
I guess it is fixed along with #221 fix on pc.
Cuz teleport seems to happen when it detects 3 units in an area

**Comment by pablorealini** [comment]
@sunnydaler Yes...this bug is very similar, @cigumo fixed for that particular case in PC. I implemented a fix that will fix all cases.
