### ISSUE TITLE
stage 6 (bolgur) does not end

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#274]
https://steamcommunity.com/app/1367550/discussions/1/2996543178711416461/

> So the final wave before the boss ended with a mech enemy dying to a crow while under the effect of the mind control from the mausoleum, and now the boss won't start up. My best guess is that since he was under my control when he died it didn't count as an 'enemy' dying and so the game thinks I haven't killed the last enemy yet?

**Comment by Mmlh1** [comment]
See #300

**Comment by pablorealini** [comment]
I think this could be because of intimidation, mostly because you cannot see the enemy in the screen...so probably yes.

**Comment by pablorealini** [comment]
duplicated with #300
