### ISSUE TITLE
reinforcements and heroes don't range if flying targets are very near

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#279]
![kr4-spears-not-working-too-near mov](https://user-images.githubusercontent.com/934821/97465488-d9e14880-1920-11eb-9522-84a7916d6be5.gif)

**Comment by cigumo** [comment]
TGM says it works on mobile. ??

**Comment by Mmlh1** [comment]
I would assume this is minimum range, right?

**Comment by pablorealini** [comment]
Yes, this is min_range and it's **"not a bug"**....but maybe with flying units we can do it different.....like min distance to hitPoint (actual enemy) @cigumo

**Comment by cigumo** [comment]
In the triliogy I coded a list of flags that override the min distance check (flying enemy is one of the flags). So basically the fix @pablorealini made in kr4 is the same idea.
