### ISSUE TITLE
stage 14 does not end 

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#280]
https://steamcommunity.com/app/1367550/discussions/1/4835136555203488451/

> So here is the thing: I was at level 14, and after killing the final wave, nothing happens. i have the skeleton tower, some orcs and dark knights, the sarcofagus and the fire mage( dont know if some of the towers could be related to the problem), and the hero is the Gul'dan one. That mage at the middle of the map keeps talking and casting spells on my towers, i broke all the lamps and a sheep got through my defenses.

**Comment by Mmlh1** [comment]
See #300

**Comment by pablorealini** [comment]
duplicated with #300
