### ISSUE TITLE
apex shard running in the wrong direction

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#281]
https://steamcommunity.com/app/1367550/discussions/1/2996543178712602100/

> When Ice Reapers spawn an Apex Shard from dead allied creatures, it runs the left road back to the "enemy entrance" (instead of the exit) and it causes you to loose lives.

https://cdn.discordapp.com/attachments/493772773081219073/771214413805125722/YouCut_20201029_122943199.mp4

**Comment by Mmlh1** [comment]
https://www.youtube.com/watch?v=hPBXDl3gZow
https://youtu.be/nDcqXIO1ExU?t=1023

**Comment by cigumo** [comment]
PC only

**Comment by cigumo** [comment]
fixed in 1.12.5
