### ISSUE TITLE
Angry Bee and Search_type NORMAL

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#290]
https://cdn.discordapp.com/attachments/493772773081219073/799197168312254503/ezgif.com-gif-maker_1.mp4
https://cdn.discordapp.com/attachments/493772773081219073/799211401612623892/ezgif.com-gif-maker_3.mp4

It targets the enemy spawned first.

**Comment by pablorealini** [comment]
I wonder why it was configured like that in the first place, because that was on purpose.
