### ISSUE TITLE
Shaolin Temple's previsualization is wrong

### ISSUE THREAD

**Issue by Emicon97** [cigumo/krvi#296]
Before buying the tower you're supposed to see how it will look when built. Instead, you see how it looks while being built (image taken from a YouTube video, but it happens to me, too).
![image](https://user-images.githubusercontent.com/94487044/145903613-5b273c6a-936b-4ca0-82ed-9c9fdd27f803.png)

**Comment by cigumo** [comment]
fix in master

**Comment by cigumo** [comment]
fixed in 1.12.5

**Comment by cigumo** [comment]
<img width="474" alt="Screen Shot 2022-02-24 at 16 05 33" src="https://user-images.githubusercontent.com/934821/155590646-0a81b7a7-d6d1-4914-8c50-293a72952dfb.png">

**Comment by Mmlh1** [comment]
My bad
