### ISSUE TITLE
Suggestion: change troop aggro/engagement to match first three games

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#301]
Currently in Vengeance, all troops engage the enemy that has spawned first within their block range. However, the other three games work differently (better). Namely, heroes engage the closest enemy to their rally point (which makes it possible to isolate high priority enemies and makes melee heroes good at sniping things), and all other troops engage the closest enemy to the exit (which is the most effective at preventing leaks).

**Comment by pablorealini** [comment]
Ok.
In this game "blocking" is this way: The order is first enemy in range etc etc ordered by creation time.
I can't remember how I programmed this in the first original games (not the newest version) but I can check it.

We can change this for heroes only to check the closet enemy, or should we change this for all units? Just for melee combat.

what do you think? @cigumo  @Mmlh1

**Comment by Mmlh1** [comment]
The way I remember it from the first three games is

- hero does closest to rally point
- other troops do closest to exit

In my opinion, the hero engaging closest to rally point is essential to make hero micro rewarding. The other troops would be fine with closest to exit, but also with closest to rally point in my opinion.
