### ISSUE TITLE
Wave indicators can be selected while spells are selected

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#302]
In the other games, when a spell is selected (hero spell, reinforcements, or RoF/Thunder), wave indicators cannot be selected, so that you can cast the spells close to the entrance. However, in Vengeance, if you have a spell selected and hover over the wave indicator, the spell gets deselected and the wave indicator gets selected.

**Comment by pablorealini** [comment]
This is a nice add on, for every action will be even better....moving a hero, rally, etc.
