### ISSUE TITLE
stage 6 cannot be started (only macOS on M1 chip?)

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#312]
http://support.ironhidegames.com/a/tickets/84052

> Hello - level 6. Bolgur's throne - the 1st wave button does not work. It just stays black without turning red and blinking. I have tried to quit/restart/reinstall the game and the issue is still happening.

**Comment by pablorealini** [comment]
Se sabe que es esto? supongo que es algo raro.

**Comment by cigumo** [comment]
The player says it stopped happening.
