### ISSUE TITLE
unpathable area on stage 25

### ISSUE THREAD

**Issue by AerisDraco** [cigumo/krvi#321]
The end of the water pathway on stage 25, dragon's power, is unpathable to heroes. Reinforcements and other spawned units work fine though.
![image](https://user-images.githubusercontent.com/24627148/153869076-b57055d3-9bb7-4baf-8b84-eadc3b9783a3.png)

**Comment by cigumo** [comment]
fixed!

**Comment by cigumo** [comment]
duplcate of #324
