### ISSUE TITLE
tower deselection bug on PC

### ISSUE THREAD

**Issue by AerisDraco** [cigumo/krvi#322]
Towers can be deselected in the tower room. 

Procedure for replication:
1. Equip a tower
2. Hit the now equipped tower's portrait

This creates a blank slot in the tower loadout. When loaded into the game, one of two things can happen:
1. If only one slot has been made blank, it displays that slot as locked out.
2. If more than one slots have been made blank, it resets the player's loadout to the first five towers (Shadow Archers, Orcs, Infernal Mage, Rocket Riders, DKs)

**Comment by cigumo** [comment]
fixed in 1.12.3
