### ISSUE TITLE
Cursed Bargain enemies have no SFX

### ISSUE THREAD

**Issue by AerisDraco** [cigumo/krvi#325]
I'm not sure why but everything in Cursed Bargain (Stages 26-28 and associated enemies) lacks a sound byte. Might be intentional, might not be. This is particularly glaring for the Screecher Bat, which has a distinctive sound byte in KRO but is silent here. Would it be possible to readd any SFX, particularly that one?

**Comment by cigumo** [comment]
Asked Jon about this one

**Comment by cigumo** [comment]
-lich summon
-haunted skeleton / bone carrier death effect?
-haunted gem / maybe blazing gem?
-screecher bat

**Comment by Mmlh1** [comment]
Haunted Gem seems to already use Blazing Gem, but at a very soft volume. Ghost uses the sheep death sound. Screecher Bat has a death sound, but no sound for the screech - that could potentially be copied from KRO.

**Comment by cigumo** [comment]
https://docs.google.com/spreadsheets/d/1TVyohkSfZkJdLEuXBYwUKoIWntCVU6gRcevnRTqZePY/edit#gid=0

**Comment by cigumo** [comment]
Added sounds

Enemy |   |   |  
-- | -- | -- | --
  |   | death | action
Ghost |   | puff_death_sound |  
Haunted Skeleton |   | Sound_EnemySkeletonBreak2.ogg |  
Bone Carrier |   | kr4_dwarves_sulfur_alchemist_death.caf |  
Werewolf |   | common enemie dead |  
Corrosive soul |   | Sound_EnemyRocketeer.ogg |  
Screecher bat |   | puff_death_sound | kro_sfx_bitteringrancor_screecher-scream[op5].ogg
Lich |   | kr4_frog_erudite_shot.caf |
