### ISSUE TITLE
Stage 16 Heroic/Iron Cannons don't match mobile

### ISSUE THREAD

**Issue by AerisDraco** [cigumo/krvi#336]
The Courtyard Cannons have separate profiles for the Heroic and Iron challenges on mobile which aren't preserved on Steam. Those being:
1. Towers are indefinitely stunned on mobile when hit (lasts 40s in mobile campaign mode and all modes on Steam)
2. Cost to clear is decreased to 30 in mobile iron mode

**Comment by cigumo** [comment]
see #168
