### ISSUE TITLE
Murglun True Damage

### ISSUE THREAD

**Issue by AerisDraco** [cigumo/krvi#337]
In the original beta of Rise of the Dragon on mobile in ~Sept. 2019, Murglun's damage type was changed from physical to true. However, in subsequent betas, such as the immediately-following Cursed Bargain beta, this change was not present. 

I'm not sure why it was removed but I'd like to ask for it back since she probably should have true damage, as all other dragons from the other games have it.

**Comment by pablorealini** [comment]
Murglun damage is Physical, it was a bug.
In KRV some dragons have Physical dmg, other have magical, etc.
