### ISSUE TITLE
Melee damage multipliers cast to integer values

### ISSUE THREAD

**Issue by AerisDraco** [cigumo/krvi#347]
Whenever a melee attack is affected by a damage value, the increase is cast to an integer, meaning in many cases the increase does not do anything. This is despite the stat bar updating appropriately. 
This applies to Jun'pai's Last Stand passive, Veruk's Duelist passive, and the soul upgrade One Man Army, as well as any other melee attack multipliers.

**Comment by Mmlh1** [comment]
Another notable one is the Orc Den's Lust for Combat - this entire upgrade is useless as a result.

**Comment by cigumo** [comment]
The culprit: 
KRSkillUnitAnimationMelee::execAction() calls blockedEnemy->receiveDamage(), which casts the damage value to int.

**Comment by Mmlh1** [comment]
Apparently we simply were mistaken and it works just as intended. Apologies.

**Comment by Mmlh1** [comment]
Actually, it was fixed by the new KRV team in this update! So we were correct but it was already fixed.
