### ISSUE TITLE
Melting furnace tier 4 bug on mobile version

### ISSUE THREAD

**Issue by Johnsterling22** [cigumo/krvi#348]
On the mobile version, tier 4 melting furnace does not ignore armor, only tier 1-3 ignores 75% of armor

**Comment by Mmlh1** [comment]
See also #73 - I think none of the initial Steam release bug fixes were ported to mobile, whereas the Rise of the Dragon fixes were. It might be a good idea to do this at some point, to make sure the versions are equal.

**Comment by Mmlh1** [comment]
Fixed in 1.15.0
