### ISSUE TITLE
Margosa's skill cooldowns get reset when using her ultimate

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#350]
When in beast form, her skill cooldowns do not charge. Even worse, they get reset when exiting beast form.

**Comment by pablorealini** [comment]
Not a bug, this was on purpose.

**Comment by Mmlh1** [comment]
It does make Margosa very bad, sadly - her skills will only really be used maybe once before the ultimate is activated again. And it's counterintuitive to say the least when her skills are charged before the ultimate is used, and are no longer charged after it ends. I would understand the cooldowns not charging during the ultimate, but being fully reset seems weird to me.

**Comment by gersonrpg** [comment]
We should change this behavior so Margosa's skills don't reset their CD. You are right, it makes no sense and it is no considered in her balance sheet
