### ISSUE TITLE
store tip shown in apple arcade version

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#353]

**Comment by pablorealini** [comment]
Este debería de ser fácil de arreglar calculo. @cigumo

**Comment by cigumo** [comment]
Si, le pongo ifdef con lista de i18n keys a excluir en los tips según la plataforma.

**Comment by cigumo** [comment]
Es el TIP_12: "You can use the powerful items of the shop in battle. They can help you turn the odds in your favor!"

**Comment by cigumo** [comment]
fixed in 1.15.5.14
