### ISSUE TITLE
New levels sometimes don't end when they should

### ISSUE THREAD

**Issue by cthulhu94401** [cigumo/krvi#366]
I've had this happen at least 3 different times. Once on the second level and twice on the third of the most recent content update.  After the final wave, the game just idles--everything works -- you can move the hero and click on ui elements  (upgrade towers, move troop rally points, etc) it's just the game doesn't end even though there are no more mobs spawning.

I think in all 3 cases I had the new hero.  This was on the windows/steam version.

**Comment by Mmlh1** [comment]
See #300 as well

**Comment by pablorealini** [comment]
This is duplicated with #300 so I will close it.
Also we already implemented a code to be able to fix this issues.
