### ISSUE TITLE
Level 31 plants can chain teleports

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#368]
https://user-images.githubusercontent.com/40719238/193821475-c4405e8a-5068-4b4b-9f0a-6f42857f095c.mp4

See the Prehistoric Dwarf here. I don't think this is intended, as it rarely happens and there is a modifier to prevent this kind of stuff. Lengthening that modifier could mess up 30 iron, though.

**Comment by cigumo** [comment]
confirmed by the designer that it was made on purpose this way
