### ISSUE TITLE
Miners go straight to the exit after being spat by plants

### ISSUE THREAD

**Issue by Emicon97** [cigumo/krvi#374]
I'm not sure why this happened, but after calling a wave early in The Original World, miners from the previous wave were starting to get swallowed and sent to another path by the just awaken plant. That's normal, but in one occasion the miners moved underground really fast towards the exit and never came out off the ground, thus causing to lose several lives.

**Comment by Mmlh1** [comment]
See #311 as well

**Comment by Mmlh1** [comment]
https://github.com/cigumo/krvi/assets/40719238/d46e3e96-3b9f-48c6-8651-6bb31d6c2092

**Comment by Mmlh1** [comment]
Presumably fixed in 1.15.0, but it is really hard to test if it is truly gone.
