### ISSUE TITLE
Great-T finale enemies sometimes stuck indefinitely at start of path

### ISSUE THREAD

**Issue by Lassoloc** [cigumo/krvi#376]
Have played the level twice, same thing happened both times. Enemies spawned while Great-T is on the field (that is, after wave 15) are stuck at the start of the path. Since the start of the path is not off-screen on this map and is instead hidden behind scenery, the enemies can be clicked (or even seen on the bottom path). Defeating Great-T didn't kill all of the enemies: both times, as the level was ending, two groups of three Quarry Workers entered the path (and moved correctly), with a sliver of health remaining (this part is effectively visual as the game correctly ended the level and ignored the living enemies on the path)

![20230912214120_1](https://github.com/cigumo/krvi/assets/72823326/0c207c8c-5518-4213-b99e-28cabfddb399)
![20230912221859_1](https://github.com/cigumo/krvi/assets/72823326/8e21911c-d11f-4ba1-a7e1-24715383d343)

**Comment by Mmlh1** [comment]
Fixed in 1.15.0
