### ISSUE TITLE
Level 15 (Lightseeker Camp) boss wave does not spawn properly on PC

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#377]
The launch_waves on Gerald is based on nodes travelled along the path. Since he spawns at a later node on PC, the first few enemy waves are never launched.

**Comment by Mmlh1** [comment]
By the way, there is a single defined spawn position in one of the launched waves, which does not work on PC either.

**Comment by cigumo** [comment]
fixed in 1.15.0 (18)
