### ISSUE TITLE
Missing Deep Devils stage briefing icon, duplicate Rotten Forest one

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#379]
not that this is important, but there is a duplicate icon of Rotten Forest in the stage_briefing file, yet there is no Deep Devil's icon. Does not really matter but in the case of future DLC's, it may cause some confusion if Deep Devil's Reef is ever used in an iron challenge.

**Comment by pablorealini** [comment]
map_levelselect_iron_towers_0017.png
