### ISSUE TITLE
stage 13: unselectable area

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#38]
https://streamable.com/4rh7b5

**Comment by cigumo** [comment]
<img width="573" alt="Screen Shot 2020-09-03 at 1 31 53 PM" src="https://user-images.githubusercontent.com/934821/92142202-daaaa200-ede9-11ea-99ef-b507b8ee47cc.png">

**Comment by cigumo** [comment]
fixed in 1.9.9.3
