### ISSUE TITLE
Offset when hitting flying enemies with Soul Impact

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#380]
![image-1](https://github.com/cigumo/krvi/assets/934821/6461630e-a44d-4d3e-a63c-e5e7b59ebd05)

**Comment by Mmlh1** [comment]
The flying enemies also just do not get hit by Soul Impact. It seems the point where Soul Impact targets and the point that needs to be in the blast radius for flying enemies to be hit have moved further apart in 1.15.

This also applies to all other explosions, not just Soul Impact.

**Comment by Mmlh1** [comment]
Lito fixed a bug with flying enemies and ground explosions I believe so this may be solved as a result.
