### ISSUE TITLE
Rotten Forest misses a subpath in Dragon's Boneyard 

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#381]
Mmlh recommeds increasing the range to 300.

<img width="698" alt="Screenshot 2023-12-20 at 12 10 14" src="https://github.com/cigumo/krvi/assets/934821/be9eb990-d7a0-4829-924d-509651edec13">

**Comment by pablorealini** [comment]
We already discussed this issue. Sadly the problem here is a bad design, the roads are too wide.
We can increase the range but It will just mitigate a little bit the problem...and the GD aren't sure about increasing the range since it might create a balance issue. Will come back later on this one.

**Comment by gersonrpg** [comment]
Tower range increase was approved after the revision of the Beta testers rebalance sheet. Even as Pablo is right in terms of paths being too wide, we can address this issue increasing a bit the range. 
New range: 320

**Comment by pablorealini** [comment]
We increased the range.
