### ISSUE TITLE
Tesla Coils attack enemies inside pyramid in The Lost Empire

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#385]
<img width="105" alt="Screenshot 2023-12-20 at 12 37 34" src="https://github.com/cigumo/krvi/assets/934821/75c3ffef-03dc-4336-9213-6b363880e6a4">

**Comment by cigumo** [comment]
Check if it's just pc or mobile too.

**Comment by Mmlh1** [comment]
Should be both, I believe this is a result of the slightly increased range of the coils. But the upside of the slightly increased range is imo greater than this minor downside.
