### ISSUE TITLE
enemy tipcard wrong info

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#39]
![Screenshot_20190413-142840_Vengeance](https://user-images.githubusercontent.com/43391939/94387582-88109b80-0185-11eb-835b-cc7a31cefe20.jpg)
- [x] Winter_lord. it doesn't have immunity. only has 85 points for each type.							

![20200902184520_1](https://user-images.githubusercontent.com/43391939/92017335-92aa6180-ed8e-11ea-938b-71bda07b19dc.jpg)
- [x] frost_giant: high armor -> medium armor

![20200902175645_1](https://user-images.githubusercontent.com/43391939/92017404-b1105d00-ed8e-11ea-92be-f9e7ed6c366c.jpg)
- [x] draugr: medium magic resist. -> high magic resist.

![20200903010649_1](https://user-images.githubusercontent.com/43391939/92017481-d1401c00-ed8e-11ea-8425-35268a4b286a.jpg)
- [x] hunting_dog: medium magic resist. -> low magic resist.

![20200903010540_1](https://user-images.githubusercontent.com/43391939/92017600-fcc30680-ed8e-11ea-976c-9011ba64e167.jpg)
- [x] elite_footman:  medium armor -> low armor

![20200903021912_1](https://user-images.githubusercontent.com/43391939/92017682-18c6a800-ed8f-11ea-8111-c61000c009a4.jpg)
- [x] devoted_priest: high magic resist. -> medium magic resist.

![20200903021646_1](https://user-images.githubusercontent.com/43391939/92017790-3c89ee00-ed8f-11ea-8f27-9e7da86dcba3.jpg)
- [x] elven_warrior: medium magic resist. -> low magic resist.

![20200903235852_1](https://user-images.githubusercontent.com/43391939/92161116-19cd0780-ee6b-11ea-9cf8-8a491c8b2875.jpg)
- [x] high_sorcerer: high armor -> medium armor

![20200904052723_1](https://user-images.githubusercontent.com/43391939/92164035-a1b51080-ee6f-11ea-998f-dfb87545c457.jpg)
- [x] warden: medium armor -> high armor

**Comment by Mmlh1** [comment]
Fixed in 1.15.0
