### ISSUE TITLE
Hero can be selected with keys while under polymorph

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#390]
You can still press Space to view your Hero even when they're under polymorph (And barracks if you spam left click on them). Is it intentional?

**Comment by pablorealini** [comment]
Maybe this is fixed with[ this commit](https://github.com/ironhidegames/issues-kr4/issues/439)? please check @cigumo

**Comment by cigumo** [comment]
> Maybe this is fixed with[ this commit](https://github.com/ironhidegames/issues-kr4/issues/439)? please check @cigumo

Yes. It fixes it for PC.
