### ISSUE TITLE
Jack O'Lantern ultimate does nothing at level 0

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#400]
The ultimate just runs through enemies without affecting them. All other levels work fine.

**Comment by Mmlh1** [comment]
Just checking, apologies if this is undesirable - did you also notice that the ultimate has the shifted level thing where the last value in the damage array is used for level 0?

**Comment by pablorealini** [comment]
No, the problem was that the skill was not working at level = 0.

**Comment by Mmlh1** [comment]
Yes, but it was also dealing 40 damage per tick at level 3 rather than the expected 60, and 20 at level 2 rather than the expected 40. So I assume it's also shifted by one level like Grosh. I can make a new issue for it.

**Comment by pablorealini** [comment]
Don’t worry. I checked it and the damage right now is the expected.

**Comment by Mmlh1** [comment]
Ah perfect!
