### ISSUE TITLE
Soldiers turned to sheep by great sorcerers and later upgraded run outside the screen in a loop

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#403]
I was at level 25 "Dragon Power" in heroic challenge and placed elite stalkers before launching waves. When the great sorcerers arrived, they logically turned some of my troops into sheep. However, I upgraded the building while the sheep were still on the ground. This had the effect of turning the sheep back into a troop, except that the troop ran all the way out of the field. It then reappeared in a loop and continued to run out of the field, making it impossible to use it without upgrading the building again. I don't know if you've heard of this, but it works on all buildings with troops, including the swamp monster (yes, I've tested them all).

**Comment by cigumo** [comment]
Should be fixed in 1.15.4

**Comment by Mmlh1** [comment]
Yeah this can be reproduced before 1.15.4 but not after. Can it be closed?
