### ISSUE TITLE
Juggernaut missiles target but cannot hit flying

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#406]
https://cdn.discordapp.com/attachments/1172533591440371792/1190373451412811847/2023_12_29_20_17_51_trim.mp4?ex=65a190aa&is=658f1baa&hm=82f10d2244108ceafc6d6490b4ef44bf5d521c9d68bed533407a475e907f8f4d&

Presumably still related to the flying enemies + explosions bug.

**Comment by pablorealini** [comment]
This is not related to that bug. This bug was probably there from launch...fixed.

**Comment by Mmlh1** [comment]
Ah, thanks for the info!
