### ISSUE TITLE
Tramin missiles retargeting is very poor

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#409]
https://github.com/ironhidegames/issues-kr4/assets/40719238/e3ee4014-f44d-42ca-b4ab-97e711911bee

They need to move over like five pixels to hit the other enemy but they do not. They also deal single target damage rather than area damage. Would be great if the retargeting could be improved, or mitigated by giving them damage in an area.

**Comment by pablorealini** [comment]
This is not easy request. Missiles in KRV work in a different way than KR1, we don't retarget in midair.
Maybe we can implement something in the future but not right now.

Will talk to GD about area damage.

**Comment by gersonrpg** [comment]
Yes, it should use an area dmg, even a small one should help being useful if the original target dies.
We can try an area damage of 40 and test it

**Comment by pablorealini** [comment]
ok, I added area damage.

**Comment by Mmlh1** [comment]
I don't have my laptop at hand currently but Doom Tank has a very similar missile skill and I don't know if that has area damage. If not, maybe that can get area damage too? But it might very well already have area damage, I just forgot if it does.

**Comment by pablorealini** [comment]
heat_missiles ? There is no area damage there. @gersonrpg 
I Agree that we should apply the same area damage.
