### ISSUE TITLE
Weird targeting priority on level 33

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#410]
https://github.com/ironhidegames/issues-kr4/assets/40719238/5584f5e3-4f73-497f-ad6f-db8d44cd3186

For some reason, the Goblirangs target enemies way further back, without having any kind of targeting priority specified in the file. This also does not seem to happen on other levels, and it does not look like the length difference to the different exits is that large? Maybe it is but visually this does not seem to be the case.

**Comment by Mmlh1** [comment]
This is not specific to the Goblirangs, it looks like the difference in path lengths is just a lot larger than I would expect from the visual.

**Comment by pablorealini** [comment]
This issue is only on PC, probably a problem with path length.
Can you test it in mobile?

**Comment by Mmlh1** [comment]
I will test mobile and I will visualise the paths to check myself (I wrote my own thing to do that).

**Comment by Mmlh1** [comment]
![image](https://github.com/ironhidegames/issues-kr4/assets/40719238/f493d98b-5c28-40b0-80d7-dfbc09ea3ba8)
These are the paths on pc. The difference in number of nodes is about 7, so it should not target with such a large difference I think.

**Comment by Mmlh1** [comment]
I do not see it on mobile. These are the mobile paths:
![image](https://github.com/ironhidegames/issues-kr4/assets/40719238/5203527f-9dc8-492b-a59f-ba03d41cb2b7)
Those differ by about 9 nodes.

**Comment by cigumo** [comment]
evaluate making path longer on pc as a simple fix

**Comment by cigumo** [comment]
nodes distance was wrong in path. let's check it with the fixed distance in 1.15.5.4

**Comment by Mmlh1** [comment]
Seems fixed to me

**Comment by Mmlh1** [comment]
Can this be closed?
