### ISSUE TITLE
hero_tank expendables have no regeneration

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#413]
Unlike basically all other allied units and summons, they have no regeneration when idle. Is this intended? Would be nice if they could get idle regeneration.

**Comment by pablorealini** [comment]
Likely a design decision.

**Comment by gersonrpg** [comment]
It's better to keep consistency that they have regen as other units I've checked how they work and their balance and it makes no difference in terms of units persistance in stage or effectiveness.

**Comment by gersonrpg** [comment]
@pablorealini on the other hand we should check how they stand around the tank as they usually get covered by the bulky hero. They can be more enjoyable if look for positions a bit more away from the hero, some nodes nearer the start of the path
