### ISSUE TITLE
Zombies can spawn out of range

### ISSUE THREAD

**Issue by Emicon97** [cigumo/krvi#416]
It's not that they just spawn in range but then walk out of it, sometimes they even spawn out of range and even walk away.

![Bad zombie, bad](https://github.com/ironhidegames/issues-kr4/assets/94487044/d8470304-0630-44ba-af2c-8ee4768976c1)

**Comment by pablorealini** [comment]
This is only for the random zombies spawned and not for enemies the died near the tower.
For died enemies It checks against the tower range and for random is a different logic.

We can change random to be also inside the range....but it may look really bad in some situations ...all the zombies together...I am not sure about changing this to be honest....

**Comment by Emicon97** [comment]
Well, the main issue with the random zombies is that they can just ruin your strategy by appearing in unwanted paths. I personally wouldn't mind having all of my zombies in one place, all the opposite. And for example, Rocket Riders, Sandworm Hollow and Ignis Altar would also like it better to have them clustered together.

**Comment by pablorealini** [comment]
I will test it, this is not a hard fix.
