### ISSUE TITLE
Clipping on Kazan Mines entrance (Stage 3)

### ISSUE THREAD

**Issue by AerisDraco** [cigumo/krvi#42]
Warhammer Guards (and maybe others?) clip through the northern entrance when first spawning.

**Comment by cigumo** [comment]
the alpha is a little darker than it should.

**Comment by cigumo** [comment]
<img width="292" alt="Screen Shot 2020-09-16 at 8 37 27 AM" src="https://user-images.githubusercontent.com/934821/93332210-e342a580-f7f7-11ea-8529-42ce47b7f315.png">

**Comment by cigumo** [comment]
fixed in 1.9.9.8
