### ISSUE TITLE
Doom Tank ult is very inconsistent

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#424]
It drops a few patches of flame (9 I believe), and they spread out relatively evenly over the subpaths, but each patch only has area 40. Hence, enemies can visually be in the middle of an inferno, but take no damage, because on their subpath, there is nothing there. This feels a bit weird and can make using this ultimate way more random than you would expect, which is not a nice experience for the player.

**Comment by pablorealini** [comment]
mmmm I think the area is to be hones, we can maybe improve it a little bit but its fine.... Random is not an enemy in games.

<img width="364" alt="Screenshot 2024-01-11 at 12 46 24" src="https://github.com/ironhidegames/issues-kr4/assets/12350808/183bf242-27fb-4117-830c-4795e94ca14d">
<img width="416" alt="Screenshot 2024-01-11 at 12 46 05" src="https://github.com/ironhidegames/issues-kr4/assets/12350808/95fd823c-8123-4ff2-833a-24ea0de6f9d5">
<img width="348" alt="Screenshot 2024-01-11 at 12 46 41" src="https://github.com/ironhidegames/issues-kr4/assets/12350808/650a0c2c-9400-4c1b-86a2-6de0e6722913">

**Comment by pablorealini** [comment]
Increasing areas from 40 to 55 looks better.
<img width="331" alt="Screenshot 2024-01-11 at 12 53 45" src="https://github.com/ironhidegames/issues-kr4/assets/12350808/eee81587-3c33-4c80-b2e9-7c3ac01527b3">
<img width="386" alt="Screenshot 2024-01-11 at 12 53 19" src="https://github.com/ironhidegames/issues-kr4/assets/12350808/9cbc0e8a-388c-4d81-bad3-0473b156ba1f">
<img width="267" alt="Screenshot 2024-01-11 at 12 53 32" src="https://github.com/ironhidegames/issues-kr4/assets/12350808/2a397233-ff07-4a53-b8bb-36ff5668c05b">

**Comment by Mmlh1** [comment]
Yeah I think that looks good!
