### ISSUE TITLE
Restarting a level crashes the game

### ISSUE THREAD

**Issue by Emicon97** [cigumo/krvi#425]
This happens on PC (Steam) at least. It usually happens when I pause and immediately try to restart.

**Comment by Mmlh1** [comment]
Which levels have you seen it on?

**Comment by Emicon97** [comment]
Last time happened in Ancient Ghosts iron. I will come back and add more levels in the future, but I have the vague idea that I've seen it happening in many others. It might be related with leaks or Tesla Coils, but that's too much guessing to me.

**Comment by Emicon97** [comment]
Duplicate of #264
