### ISSUE TITLE
Incorrect/missing localization on PC

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#426]
- [ ] ![image](https://github.com/ironhidegames/issues-kr4/assets/40719238/6af51a9a-6962-4b51-9fef-f48e15294709)
34 iron
- [ ] ![image](https://github.com/ironhidegames/issues-kr4/assets/40719238/c5c88ead-41c6-4209-a141-90bb4b36b26d) ![image](https://github.com/ironhidegames/issues-kr4/assets/40719238/c7b11301-5694-4230-b114-16a4948195ce) Mortemis Grim Presence

**Comment by cigumo** [comment]
fixed in 1.15.5.6

**Comment by Mmlh1** [comment]
Both are fixed, so I assume this can be closed.
