### ISSUE TITLE
Mirage level 33 wave 3 spawn cinematic walks weirdly

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#428]
https://github.com/ironhidegames/issues-kr4/assets/40719238/0e94a20b-e213-48b2-9903-87d547d93d8e

**Comment by pablorealini** [comment]
This is not a bug. 
Mirage has a kill that if she has nothing to do she walks side to side instead of being there just standing.
Here the bug is that she is no casting the skill of calling the nomads.

I am closing this issue.

**Comment by cigumo** [comment]
fixed in PC with #427

**Comment by Mmlh1** [comment]
Ah thanks for the explanation, makes perfect sense!
