### ISSUE TITLE
Bone Flingers' Walking Dead can use Nomad paths in level 34

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#429]
![image](https://github.com/ironhidegames/issues-kr4/assets/40719238/ad36c23c-a2f5-48ee-8fca-f996e58e9802)

**Comment by pablorealini** [comment]
Pc and mobile?

**Comment by Mmlh1** [comment]
Seen on PC, will test mobile

**Comment by pablorealini** [comment]
Ok, I know what is happening...they are not using that path, they are spawning on that node and then going to a primary path, right? This is something I already notice but I don't know if we will change this...is a very minor issue and not a bug to be honest.

**Comment by pablorealini** [comment]
I will improve this.
