### ISSUE TITLE
Shatra abduction issues

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#430]
- [x] abduction sometimes fails: https://github.com/ironhidegames/issues-kr4/assets/40719238/afe1ee1d-4aef-4a4b-ae51-ba7c30c706c1

- [x] abduction does not enforce the target cap of 3: https://github.com/ironhidegames/issues-kr4/assets/40719238/5c5ee9b4-3a8e-4e14-9b14-022b12eecb69

**Comment by pablorealini** [comment]
The first its because of a bad configuration in the crowd targets settings...
Range 200 is just too big and in this case the skill is considering the middle of the 3 enemies (golem and 2 soldiers from the barrack) I will reduce the range for searching crowd units.

**Comment by cigumo** [comment]
fixed in 1.15.5.8
