### ISSUE TITLE
23 iron is impossible with free heroes after Soul Impact fix (#289)

### ISSUE THREAD

**Issue by Emicon97** [cigumo/krvi#432]
The cooldown reduction is just a bit too low. According to Mmlh, 2.5s or 3s reduction instead of 2 could solve this.

**Comment by Mmlh1** [comment]
Maybe 2.7 or 2.75 would do it, I will test in the Steam build

**Comment by Emicon97** [comment]
Cooldown reduce has an integer key, not a float (or rather, real). I tried what you said, but even 2.9 is way too different from 3. Also, it's funny that the 2s seems to be harcoded, even after changing it to 3 it still displayed 2s.

Btw, 3s does make it indeed.

**Comment by Mmlh1** [comment]
You can just change the integer to real, you know. But indeed it does display 2s sometimes even when set to 3s

**Comment by Emicon97** [comment]
Shoot, thought it would break if I changed the key.

**Comment by Mmlh1** [comment]
I still did not get it with 3s because it still seems somewhat inconsistent

**Comment by Mmlh1** [comment]
oh I think Spectre kills are hardcoded to 2s now

**Comment by Emicon97** [comment]
Yes, with 3, I can pass the first "wave", but it's really difficult to beat the whole stage. I couldn't do it yet.

**Comment by Emicon97** [comment]
Giving 3 seconds to both cooldown_reduce_soulimpact and feast_damned works just fine.

**Comment by Mmlh1** [comment]
Can confirm it is possible with 3s cooldown reduction, and this gives similar results in terms of cooldown reduction as before the refactor

**Comment by gersonrpg** [comment]
Aside from the discussion about adjusting the Soul Impact, the Iron can be passed in impossible mode with different heroes, Veruk for example.
I don't consider adjusting how Soul Impact works after the fix, now it is as it was intended.

**Comment by Mmlh1** [comment]
Indeed, it is definitely possible. Our bad.

**Comment by Emicon97** [comment]
Yes, my mistake on trying to make it work with a strategy that relied heavily on that spell recharging fast.
