### ISSUE TITLE
Sandworm ability titles are not all caps

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#436]
All ability titles for towers are all caps, except those for Sandworm, which have standard capitalization. It would probably be better if all ability titles would use consistent capitalization, does not really matter if that is all caps or standard.

**Comment by pablorealini** [comment]
Agree, I can decided if Sandworm style is better ...

<img width="657" alt="Screenshot 2024-01-11 at 09 42 39" src="https://github.com/ironhidegames/issues-kr4/assets/12350808/a6a2b125-27e8-4588-b859-bba397f75383">


<img width="719" alt="Screenshot 2024-01-11 at 09 42 53" src="https://github.com/ironhidegames/issues-kr4/assets/12350808/2b5001a0-522b-4ac3-a568-e9d9720c8f05">

**Comment by Mmlh1** [comment]
I personally slightly prefer Sandworm style but it would be more work to change all other towers than to change just Sandworm. And other people may have other preferences.

**Comment by Mmlh1** [comment]
Looks like the other games also all use all caps, so I guess that would make the most sense.

**Comment by pablorealini** [comment]
I will refactor this...I think in the tower room is better uppercase but infame its better first letter upper only.
