### ISSUE TITLE
Achievement placement is weird

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#437]
![image](https://github.com/ironhidegames/issues-kr4/assets/40719238/fff930b6-1132-4438-84a5-382bd75743c4)
I noticed it on PC, not sure about mobile.

**Comment by Mmlh1** [comment]
Windows 10, resolution 1536x864

**Comment by cigumo** [comment]
I cannot reproduce it with the same resolution or others.

**Comment by Mmlh1** [comment]
![image](https://github.com/ironhidegames/issues-kr4/assets/40719238/1c6d7ee0-3a57-4346-ba75-26f3040a548c)
Fixed itself after PC restart. Weird.

**Comment by Emicon97** [comment]
It happens every so often. I believe It'd be really difficult to reproduce
