### ISSUE TITLE
The winter queen's skill doesn't work sometimes

### ISSUE THREAD

**Issue by misaka14196** [cigumo/krvi#440]
https://github.com/ironhidegames/issues-kr4/assets/156454806/ca63e8b6-6129-44f2-82eb-5c66cc5e519d

The skill 'unit_necromancer' doesn't work without the tag 'custom_event'. For instance, the winter queen does not create apex shards when our units are killed around her.

**Comment by pablorealini** [comment]
I think this is fixed in the latest version. What version are you trying? Can someone confirm? @Mmlh1

**Comment by Mmlh1** [comment]
This indeed works in the latest version.

**Comment by misaka14196** [comment]
I’ve tested this skill on the version 1.15.04(Android) and 1.15.4.2(Steam). It works on neither of them. I'm not sure whether they are the latest version.

**Comment by pablorealini** [comment]
We have a new version in beta: 1.15.5.10 in steam
