### ISSUE TITLE
Graphical glitch stage 34 on PC

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#446]
![image](https://github.com/ironhidegames/issues-kr4/assets/40719238/9c894964-fed2-44e2-96e9-9e3fa79d97fa)

**Comment by cigumo** [comment]
<img width="107" alt="Untitled" src="https://github.com/ironhidegames/issues-kr4/assets/934821/705f2ab4-58c1-4c75-b967-686ce13ee1cd">

**Comment by cigumo** [comment]
<img width="138" alt="Untitled 2" src="https://github.com/ironhidegames/issues-kr4/assets/934821/d7616894-4d61-498b-8ca2-63389b8a1625">

**Comment by cigumo** [comment]
fixed in v1.15.6.4
