### ISSUE TITLE
stage 15: a pointer for mercenary

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#45]
it would be nice to have a new pointer for placing mercenaries.
the basic hand pointer cannot tell whether the mercenaries are selected, cancelled, or anything.

I made one myself
![mercenary pointer](https://user-images.githubusercontent.com/43391939/92145889-d61ad380-ee53-11ea-9637-60e8143f249c.png)

**Comment by cigumo** [comment]
fixed in 1.9.9.9
