### ISSUE TITLE
①Junpai's Tidal Wave has no damage and ②The damage of War Zeppelin is wrongly multiplied

### ISSUE THREAD

**Issue by steplight** [cigumo/krvi#452]
①Tidal Wave
I found that "modifier_tick" now can only recognize the first modifier, which means Junpai's Tidal Wave cannot cause damage ( Stunning is the first modifier ).
It seems that Margosa's Myst Form also lose its second modifier for adding miss-chance to enemies.

②Goblin War Zeppeplin
The “damage_multiplier” will affect it twice, leading to a higher number. Besides, after losing the bonus, its damage will get lower than its origin. The video will show it in details.

I would appreciate it if these problems can be fixed as soon as possible.

https://github.com/ironhidegames/issues-kr4/assets/159705093/b8a2d55a-1f33-4ebb-8697-5fd90a07c819

https://github.com/ironhidegames/issues-kr4/assets/159705093/837774f5-0ada-4480-966c-fa5566f00de1

**Comment by misaka14196** [comment]
I've tested this before. Actually, only the last (existing) damage multiplier will affect it twice, and only the last ended damage multiplier will be lost twice. For instance, if modifier A is 'deal 200% damage for 5s', and modifier B is 'deal 400% damage for 6s', then the actual damage will be like this:  100%--(A start)--400%--(B start)--3200%--(A end)--800%--(B end)--25%
