### ISSUE TITLE
Hero Margosa hangs on level "Frozen Rapids" (Steam)

### ISSUE THREAD

**Issue by Lecov** [cigumo/krvi#457]
I am writing to report a bug I encountered while playing the game. The issue revolves around the hero I control failing to respawn properly after being defeated. 

(El usuario envió un video donde Margosa permanece en el mismo lugar y además no puede seleccionarla).
![Margosa hangs](https://github.com/ironhidegames/issues-kr4/assets/154907709/0dda0828-9e12-44f4-b77f-476cb706b31e)
![Margosa hangs2](https://github.com/ironhidegames/issues-kr4/assets/154907709/e8ee5f3b-12b5-4d91-8f16-d218ede58fd6)

**Comment by pablorealini** [comment]
fix it.
