### ISSUE TITLE
Djinni spawn animation on Oasis Sape looks weird on Steam.

### ISSUE THREAD

**Issue by Emicon97** [cigumo/krvi#458]
![imagen](https://github.com/ironhidegames/issues-kr4/assets/94487044/060b47d5-f08e-4746-bb21-2d5c62f33096)

**Comment by pablorealini** [comment]
This is not a spawn animation, is this a mirage nomad hanged while doing the dodge?

**Comment by Emicon97** [comment]
Oh, yes, I was wrong. It isn't a hanged nomad though, it seems to me that for some reason, part of their animations can appear there when the Djinni spawns.

https://github.com/ironhidegames/issues-kr4/assets/94487044/91594e01-3887-4df3-a98a-0a9aec76f249

**Comment by pablorealini** [comment]
Ok, I think those are not nomads but Shaolin monks.
