### ISSUE TITLE
Frozen Land displays an up arrow when selected

### ISSUE THREAD

**Issue by AerisDraco** [cigumo/krvi#47]
Fairly certain it shouldn't display a tower's upgrade arrow, but rather a shovel.

**Comment by sunnydaler** [comment]
![Screenshot_20200904-034641_Vengeance](https://user-images.githubusercontent.com/43391939/92154796-585dc480-ee61-11ea-8f46-05011ed7e1db.jpg)

**Comment by cigumo** [comment]
this is the same in mobile. 
won't fix for now.
