### ISSUE TITLE
Snack Hour doesn't target max crowds

### ISSUE THREAD

**Issue by Emicon97** [cigumo/krvi#475]
According to the files, it should, but for some reason, it doesn't work like that.

**Comment by Mmlh1** [comment]
Snack Hour does not target max crowd. Magic Carpets, Arkuz (axe rain and dragon), Arcane Magus (teleport and main attack), Spoon (Magnus), Infernal Portal, Tramin Flashbang, Jun'Pai wave and banner, Jack Explosive Head, Dianyun Divine Rain do.
