### ISSUE TITLE
Towers cannot be built on (some) levels with pre built towers

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#498]
https://www.reddit.com/r/kingdomrush/s/DOR2ZBNOiP

If the level mode defines towers to be placed at the start of the level, on certain levels, only DLC towers can be built.

**Comment by Mmlh1** [comment]
https://www.reddit.com/r/kingdomrush/comments/1fisete/bug_on_the_heroics_for_levels_911_all_towers/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=1

**Comment by Mmlh1** [comment]
https://www.reddit.com/r/kingdomrush/s/yYJ8oPN064

**Comment by cigumo** [comment]
fixed in 1.16.2.4
