### ISSUE TITLE
Pit Lord stays when resetting upgrades

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krvi#515]
![image](https://github.com/user-attachments/assets/1b08a51d-8e57-4cfd-aaf0-553ce1c7691a)
![image](https://github.com/user-attachments/assets/e5568c06-5f0e-4065-9f52-9980e4130a07)
Reported by Derpy

When upgrading the Hellion Trident side of the upgrades, and then resetting the level 2 upgrade (better goonies), Pit Lord does not get unupgraded.

**Comment by pablorealini** [comment]
fixed.
