### ISSUE TITLE
hero_asra: spiderbite attack sfx delay

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#56]
[units_settings]

					<key>sound_start</key>
					<dict>
						<key>id</key>
						<string>hero_asra_spiderbite_attack</string>
						<key>delay</key>
						**<real>0.3</real>**

delay should be 0.9

I counted the frames and found the slashing attack begins 27 frames later.
0.9s delay makes the sound syncs with the action.

**Comment by cigumo** [comment]
fixed in 1.9.9.4
