### ISSUE TITLE
hero ultimate: pointer decal size

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#58]
![Untitled](https://user-images.githubusercontent.com/43391939/92322014-a9d8a000-f069-11ea-8f9d-caf61a1cdd62.png)
I think it is better to use the big one for AoE ultimate powers, and the small one for unit-summoning ulties.

the followings are bad examples

- hero_asra: area poisoning
![2020_09_06_17_39_07_942](https://user-images.githubusercontent.com/43391939/92322323-80b90f00-f06b-11ea-88dd-7e523dddee46.png)

- hero_oloch: area teleport 
![2020_09_06_18_08_10_265](https://user-images.githubusercontent.com/43391939/92322406-f91fd000-f06b-11ea-8127-274dbcedee60.png)

- hero_mortemis: summons a unit
![2020_09_06_18_10_43_482](https://user-images.githubusercontent.com/43391939/92322478-5fa4ee00-f06c-11ea-8426-1f9de2931ddc.png)

- hero_murglun: area instakill
![2020_09_06_18_15_10_396](https://user-images.githubusercontent.com/43391939/92322576-0b4e3e00-f06d-11ea-939a-ce79699cf5b8.png)

- hero_jigou: covers an area with ice
![2020_09_06_18_20_49_839](https://user-images.githubusercontent.com/43391939/92322699-cd9de500-f06d-11ea-8aa9-a9e76445eb4e.png)

- hero_naga: I am not sure about this one. It summons a kraken that deals area damage over time.
![2020_09_06_18_18_45_785](https://user-images.githubusercontent.com/43391939/92322656-7f88e180-f06d-11ea-8db2-55ec70b89bd6.png)

**Comment by cigumo** [comment]
left hero_naga as it was (point) but changed the rest
1.9.9.4
