### ISSUE TITLE
hero initial positions

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#67]
- [x] 1. level2_data

	(x, y) = (65, 408) to (**75**, 408)
![20200910172235_1](https://user-images.githubusercontent.com/43391939/92701003-7445f680-f38a-11ea-994c-e652065ba858.jpg)

- [x] 2. level17_data
	(x, y) = (207, 410) to (**203**, **415**)
![20200910175601_1](https://user-images.githubusercontent.com/43391939/92705866-03550d80-f38f-11ea-8eae-81866461ed25.jpg)

- [x] 3. level20_data
	(x, y) = (950, 466) to **(961,** **465**)
![20200910175820_1](https://user-images.githubusercontent.com/43391939/92706393-6fd00c80-f38f-11ea-9822-40841ff15288.jpg)

- [x] 4. level21_data
        (x, y) = (950, 293) to (**961**, **301**)  
![20200910175820_1](https://user-images.githubusercontent.com/43391939/92706746-baea1f80-f38f-11ea-8cb5-3ec9456da471.jpg)

- [x] 5. level22_data
        (x, y) = (950, 282) to (**961**, **275**)  
![20200910180431_1](https://user-images.githubusercontent.com/43391939/92707443-406dcf80-f390-11ea-97a1-76d77a474fad.jpg)

**Comment by cigumo** [comment]
awesome :D thanks sunny!

**Comment by cigumo** [comment]
fixed in 1.9.9.5
