### ISSUE TITLE
description errors

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#69]
## Done
- [x] HERO_VERUK_SKILL_PASSIVE_1_DESCRIPTION = "When Veruk is close to death, he enters a state that regenerates his Health constantly."
hero_veruk always regenerates.
> 		                        <string>warlust</string>
> 					<key>key</key>
> 					<string>regeneration</string>
> 					<key>override_conditions</key>
> 					<true/>

- [x] REINFORCEMENT_WARMONGER_ZAPPER = "Zapper"
TOWER_WARMONGER_BALLOON_LEVEL4_PARACHUTE_DESCRIPTION = "Summons a Goblin Zapper onto the battlefield."
TOWER_WARMONGER_BALLOON_LEVEL4_PARACHUTE_DESCRIPTION_1 = "Summons a Goblin Zapper onto the battlefield."
Goblin Sapper is named Goblin Zapper.

- [x] TOWER_ELVES_BARRACK_LEVEL4_BACKSTAB_DESCRIPTION_1 = "Harassers now counter the next attack when dodging an enemy's melee hit, dealing 25-35 damage."
TOWER_ELVES_BARRACK_LEVEL4_BACKSTAB_DESCRIPTION_2 = "Harassers now counter the next attack when dodging an enemy's melee hit, dealing 40-60 damage."
elite harassers' backstab deals 10-15 at skill lvl 1 and 20-30 at skill lvl 2.
			
>                               <string>backstabHit</string>
> 					<key>min_damage</key>
> 					<array>
> 						<integer>0</integer>
> 						<integer>10</integer>
> 						<integer>20</integer>
> 					</array>
> 					<key>max_damage</key>
> 					<array>
> 						<integer>0</integer>
> 						<integer>15</integer>
> 						<integer>30</integer>

- [x] HERO_ASRA_SKILL_QUIVER_OF_SORROW_1_DESCRIPTION = "Asra breaks the armor of the target by 2 points on each ranged attack she hits."
HERO_ASRA_SKILL_QUIVER_OF_SORROW_2_DESCRIPTION = "Asra breaks the armor of the target by 4 points on each ranged attack she hits."
HERO_ASRA_SKILL_QUIVER_OF_SORROW_3_DESCRIPTION = "Asra breaks the armor of the target by 6 points on each ranged attack she hits."
hero_asra breaks the armor by 1/2/3 points on each ranged attack. 
						
> 	                                        <key>skill_damage_armor</key>
> 						<array>
> 							<integer>1</integer>
> 							<integer>2</integer>
> 							<integer>3</integer>

- [x] HERO_TRAMIS_SKILL_FLASHBANG_3_DESCRIPTION = "Throws a Flashbang at a group of enemies, stunning them for 4 seconds."
hero_tramin's Flashbang Level 3 stuns enemies for 3 seconds.
> 							<key>modifiers</key>
> 							<dict>
> 								<key>key</key>
> 								<string>stun</string>
> 								<key>duration</key>
> 								<array>
> 									<integer>1</integer>
> 									<integer>2</integer>
> 									<integer>3</integer> 

- [x] 	HERO_MARGOSA_SKILL_VAMPIRIC_TOUCH_1_DESCRIPTION = "Basic attacks now drain enemy's lives, healing her for 10% of the damage dealt."
HERO_MARGOSA_SKILL_VAMPIRIC_TOUCH_2_DESCRIPTION = "Basic attacks now drain enemy's lives, healing her for 20% of the damage dealt."
HERO_MARGOSA_SKILL_VAMPIRIC_TOUCH_3_DESCRIPTION = "Basic attacks now drain enemy's lives, healing her for 30% of the damage dealt."		
it is 20%/30%/50%.			
>                                     <key>skill_healing_custom_points_percent</key>
>						<array>
>							<real>0.2</real>
>							<real>0.3</real>
>							<real>0.5</real>

- [x] HERO_OLOCH_SKILL_MAGMA_ERUPTION_1_DESCRIPTION = "Casts an infernal spell that erupts 3 lava geysers, dealing 60 true damage to each target."
HERO_OLOCH_SKILL_MAGMA_ERUPTION_2_DESCRIPTION = "Casts an infernal spell that erupts 4 lava geysers, dealing 140 true damage to each target."
HERO_OLOCH_SKILL_MAGMA_ERUPTION_3_DESCRIPTION = "Casts an infernal spell that erupts 5 lava geysers, dealing 250 true damage to each target."
it is 20/40/60 true damage for each.
>						<key>damage_min</key>
>						<array>
>							<integer>20</integer>
>							<integer>40</integer>
>							<integer>60</integer>
>						</array>
>						<key>damage_max</key>
>						<array>
>							<integer>20</integer>
>							<integer>40</integer>
>							<integer>60</integer>

- [x] HERO_MURGLUN_SKILL_MAGMA_POOL
Murlglun's magma_pool deals up to 10/20/30 damage per second, according to the codes.
Not up to 12/24/36 damage per sec as described in hero room.

- [x] HERO_MURGLUN_SKILL_INFERNAL_HEAT
Murglun's infernal_heat deals up to 100 damage.
Not up to 50.

**Comment by cigumo** [comment]
partially fixed in 1.9.9.5

**Comment by sunnydaler** [comment]
- [ ] 	HERO_MARGOSA_SKILL_VAMPIRIC_TOUCH_1_DESCRIPTION = "Basic attacks now drain enemy's lives, healing her for 10% of the damage dealt."
HERO_MARGOSA_SKILL_VAMPIRIC_TOUCH_2_DESCRIPTION = "Basic attacks now drain enemy's lives, healing her for 20% of the damage dealt."
HERO_MARGOSA_SKILL_VAMPIRIC_TOUCH_3_DESCRIPTION = "Basic attacks now drain enemy's lives, healing her for 30% of the damage dealt."		
it is 20%/30%/50%.			
>                                                <key>skill_healing_custom_points_percent</key>
>						<array>
>							<real>0.2</real>
>							<real>0.3</real>
>							<real>0.5</real>

**Comment by sunnydaler** [comment]
- [ ] ENEMY_BOSS_WINTER_QUEEN_ENCYC_DESCRIPTION = "Free from her shackles, she is an powerful creature with only one thing in mind: to turn the kingdom into a frozen nightmare."

an --> a
