### ISSUE TITLE
dark_army_melting_furnace_tower_lvl4 - ignore_armor_points

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#73]
lvl 1~3 furnace towers ignore armor by 75%.

but lvl 4 furnace ignores 0 armor as of now.
and inflicts less damage to armored enemies than what lvl 3 furnace does.

besides, this armor ignoring factor should also apply to "burning_heat"

**Comment by cigumo** [comment]
@thehalfleprechaun says to keep level 3 values for level 4.

**Comment by cigumo** [comment]
fixed in 1.9.9.6

**Comment by Mmlh1** [comment]
For reference, not yet fixed on mobile.
