### ISSUE TITLE
prevent heroes from casting skills on the move

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#76]
- [ ] hero_jiou - ice_shard
![ice shard](https://user-images.githubusercontent.com/43391939/92942738-d25b0280-f48c-11ea-9182-03ea9ad3a1ad.gif)

- [ ] hero_oloch - hellish_infusion
![infusion](https://user-images.githubusercontent.com/43391939/92942756-d850e380-f48c-11ea-8d8e-a3e1aad12344.gif)

**Comment by cigumo** [comment]
fixed in 1.9.9.13
