### ISSUE TITLE
hero_tank_expendable2 prioritizes ranging and enemies ignore them

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#77]
https://streamable.com/l9a9a5
https://streamable.com/i5b2wk

because of this?
>					<key>should_lock_shooting</key>
>					<true/>

**Comment by cigumo** [comment]
![](https://camo.githubusercontent.com/11f684a7e33a6012781b81a884c17a90b44ab608/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3439333737323737333038313231393037332f3736323137313432363635363232333236322f756e6b6e6f776e2e706e67)

**Comment by cigumo** [comment]
reproduce:  Just move tank away to a remote place while expendables range attack enemies

**Comment by Mmlh1** [comment]
As far as I can tell, fixed in 1.15.0
