### ISSUE TITLE
"kr4_balloon_in" sfx 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#81]
- [x] on mobile, this sound is heard when a tower skill icon is tapped and highlighted in tower room. missing on pc.

- [x] this sound is used in encyclopedia on previous kr pc games. not used on krv pc.

btw, what do u think about removing kr4_balloon_out sfx from the tower room? it can be heard over the balloon_in sfx as on mobile.

**Comment by cigumo** [comment]
changes in 1.9.9.6
- removed  balloon out from tower room
- changed the encyclopedia entry click sound to balloon_in
